### PR TITLE
Pagination for MaterializeCSS

### PR DESCRIPTION
**Pull request by arandilopez**
Because material is trending.

**Note:** There's no implementation of simple pager by [MaterializeCSS](http://materializecss.com/pagination.html#!). :cry:

### CODE REVIEW

**Comment by Landish** [comment]
Can you provide also Tests? 

If there is no, Simple Pagination, maybe we can just use, arrows.

**Comment by arandilopez** [comment]
Ok @Landish... Let me write them and try to code an simple paginator with materialize. :+1:

**Comment by arandilopez** [comment]
BTW... @Landish how did you test Simple pagination?

**Comment by Landish** [comment]
For some reason, I didn't make tests for Simple pagination. I'll do it later.
Thank you so much for contribution : )

**Pull request merged**
