### PR TITLE
Paginator presenter for MaterialDesignLite

### PR DESCRIPTION
**Pull request by bonsi**

### CODE REVIEW

**Comment by Landish** [comment]
@bonsi Thanks for you contribution. 
Can you also add some Tests?

**Comment by bonsi** [comment]
@Landish Excuse the drive-by-pullrequest, somehow I overlooked the tests, Will do! Could be a couple of days though before I find the time to add them.

**Comment by Landish** [comment]
@bonsi No worries. Take your time.

**Comment by bonsi** [comment]
@Landish I've added the tests for the MaterialDesignLite paginator. A bit messy with the commits since the travis build kept failing for php 5.4 and I needed a couple of retries to get right ;)

**Comment by bonsi** [comment]
@Landish I've added the tests for the MaterialDesignLite paginator. A bit messy with the commits since the travis build kept failing for php 5.4 and I needed a couple of retries to get right ;)
I took the liberty to add some additional wrappers around the paginator but just noticed that's not the way to go since you provide other means to do that. Will take a look at that somewhere in the next few days.

**Pull request closed without merging**
